spring:
  profiles:
    active: s3Bucket
  application:
    # Application name
    name: Spring_boots
  datasource:
    # H2 Database configuration
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb
  h2:
    console:
      # H2 console settings - Access at http://localhost:8080/h2-console
      path: /h2-console
      enabled: 'true'
  devtools:
    restart:
      enabled: true
  jpa:
    # JPA Configuration
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  issuer: test@example.com
  secret_key: spring-boots

  secret: "HvFnEFgEYYrlEcJFPP/I+MB7kDyelh0j3+/Tz9uhLWYp119Aph+FlfLCz7YVI7DdEjtWQqQ4KZ+fdxEC+kNSpw==" ##임시 키
  token:
    refresh-expires: 604800000 # 7일
    access-expires: 900000 # 15분

admin:
  code: ${ADMIN_CODE} #관리자코드
